apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- statefulset.yaml
- service.yaml
- configmap.yaml

commonLabels:
  app.kubernetes.io/name: mysql
  app.kubernetes.io/component: database
  app.kubernetes.io/part-of: one-day-pub

images:
- name: mysql
  newTag: "8.0"