apiVersion: v1
kind: Service
metadata:
  name: one-day-pub-api-service
  labels:
    app: one-day-pub-api
    component: backend
spec:
  type: ClusterIP
  ports:
  - port: 8000
    targetPort: 8000
    protocol: TCP
    name: http
  selector:
    app: one-day-pub-api