apiVersion: apps/v1
kind: Deployment
metadata:
  name: one-day-pub-web
  labels:
    app: one-day-pub-web
    component: frontend
spec:
  replicas: 1  # Will be overridden by environments
  selector:
    matchLabels:
      app: one-day-pub-web
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1
  template:
    metadata:
      labels:
        app: one-day-pub-web
        component: frontend
    spec:
      containers:
      - name: web
        image: chansparcs/one-day-pub-web:latest  # Will be updated by CI/CD
        ports:
        - containerPort: 3000
          name: http
        env:
        - name: NODE_ENV
          value: "production"
        - name: NEXT_PUBLIC_API_URL
          value: "https://one-day-pub.site/api"  # Will be overridden by environments
        - name: NEXTAUTH_SECRET
          valueFrom:
            secretKeyRef:
              name: one-day-pub-secrets
              key: nextauth-secret
        - name: NEXTAUTH_URL
          value: "https://one-day-pub.site"  # Will be overridden by environments
        resources:
          requests:
            memory: "100Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "300m"
        livenessProbe:
          httpGet:
            path: /
            port: 3000
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
        readinessProbe:
          httpGet:
            path: /
            port: 3000
          initialDelaySeconds: 5
          periodSeconds: 5
          timeoutSeconds: 3
      restartPolicy: Always