apiVersion: v1
kind: Service
metadata:
  name: one-day-pub-web-service
  labels:
    app: one-day-pub-web
    component: frontend
spec:
  type: ClusterIP
  ports:
  - port: 3000
    targetPort: 3000
    protocol: TCP
    name: http
  selector:
    app: one-day-pub-web