apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: one-day-pub-prod
  namespace: argocd
  labels:
    app.kubernetes.io/name: one-day-pub-prod
    app.kubernetes.io/part-of: one-day-pub
    environment: production
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: one-day-pub-project
  
  source:
    repoURL: https://github.com/pbc1017/one-day-pub-k8s.git
    targetRevision: HEAD
    path: environments/prod
  
  destination:
    server: https://kubernetes.default.svc
    namespace: one-day-pub-prod
  
  syncPolicy:
    # GitOps: PR 머지 시 자동 동기화 (selfHeal=false로 안전성 유지) 🛡️
    automated:
      prune: true
      selfHeal: false
    syncOptions:
    - CreateNamespace=true
    - PrunePropagationPolicy=foreground
    - PruneLast=true
    - RespectIgnoreDifferences=true
    - ApplyOutOfSyncOnly=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
  
  revisionHistoryLimit: 10
  
  # 리소스 상태 모니터링
  ignoreDifferences:
  - group: apps
    kind: Deployment
    jsonPointers:
    - /spec/replicas
  - group: ""
    kind: Service
    jsonPointers:
    - /spec/clusterIP
