# ArgoCD RBAC ConfigMap
# 이 파일은 ArgoCD 설치 시 적용되는 글로벌 RBAC 정책입니다
apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-rbac-cm
  namespace: argocd
  labels:
    app.kubernetes.io/name: argocd-rbac-cm
    app.kubernetes.io/part-of: argocd
data:
  # RBAC 정책 설정
  policy.default: role:readonly
  
  # 그룹 기반 역할 매핑
  policy.csv: |
    # 관리자 그룹
    g, one-day-pub-admins, role:admin
    g, argocd-admins, role:admin
    
    # 개발팀 권한
    g, one-day-pub-developers, role:one-day-pub-developer
    g, one-day-pub-operators, role:one-day-pub-operator  
    g, one-day-pub-viewers, role:readonly
    
    # 커스텀 역할 정의
    p, role:one-day-pub-developer, applications, get, */*, allow
    p, role:one-day-pub-developer, applications, sync, one-day-pub-project/one-day-pub-dev, allow
    p, role:one-day-pub-developer, applications, action/*, one-day-pub-project/one-day-pub-dev, allow
    p, role:one-day-pub-developer, logs, get, one-day-pub-project/one-day-pub-dev, allow
    p, role:one-day-pub-developer, repositories, get, *, allow
    
    p, role:one-day-pub-operator, applications, *, one-day-pub-project/*, allow
    p, role:one-day-pub-operator, repositories, *, *, allow
    p, role:one-day-pub-operator, logs, *, one-day-pub-project/*, allow
    p, role:one-day-pub-operator, exec, *, one-day-pub-project/*, allow
    
    # 운영환경 특별 제한
    p, role:one-day-pub-developer, applications, sync, one-day-pub-project/one-day-pub-prod, deny
    p, role:one-day-pub-developer, applications, delete, one-day-pub-project/one-day-pub-prod, deny
  
  # OIDC/SSO 설정 (향후 확장용)
  # oidc.config: |
  #   name: One Day Pub SSO
  #   issuer: https://your-oidc-provider.com
  #   clientId: one-day-pub-argocd
  #   requestedScopes: ["openid", "profile", "email", "groups"]
  #   requestedIDTokenClaims: {"groups": {"essential": true}}
  
  # 관리자 사용자 정의
  users.admin.enabled: "true"
  accounts.admin: apiKey, login