apiVersion: apps/v1
kind: Deployment
metadata:
  name: one-day-pub-api
spec:
  replicas: 1
  template:
    spec:
      containers:
      - name: api
        env:
        - name: NODE_ENV
          value: "production"
        - name: DB_HOST
          value: "mysql-service"
        - name: DB_PORT
          value: "3306"
        - name: DB_NAME
          value: "one-day-pub_dev"
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "300m"