apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../base/api
- ../../base/web
- ../../base/mysql
- namespace.yaml
- ingress.yaml
# - secrets.yaml  # Removed: Secrets applied directly via SSH

patches:
- path: api-patch.yaml
- path: api-dns-patch.yaml
- path: web-patch.yaml
- path: mysql-patch.yaml
- path: mysql-hostport-patch.yaml

images:
- name: chansparcs/one-day-pub-api
  newName: chansparcs/one-day-pub-api
  newTag: dev-4c44757f50a9e0c89201e453e947990a7c08cd52
- name: chansparcs/one-day-pub-web
  newName: chansparcs/one-day-pub-web
  newTag: dev-4c44757f50a9e0c89201e453e947990a7c08cd52

namespace: one-day-pub-dev
